<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TipoReporte extends \Entities\TipoReporte implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function setComentarioSugerido($comentarioSugerido)
    {
        $this->__load();
        return parent::setComentarioSugerido($comentarioSugerido);
    }

    public function getComentarioSugerido()
    {
        $this->__load();
        return parent::getComentarioSugerido();
    }

    public function setCampoDataset($campoDataset)
    {
        $this->__load();
        return parent::setCampoDataset($campoDataset);
    }

    public function getCampoDataset()
    {
        $this->__load();
        return parent::getCampoDataset();
    }

    public function setPublico($publico)
    {
        $this->__load();
        return parent::setPublico($publico);
    }

    public function getPublico()
    {
        $this->__load();
        return parent::getPublico();
    }

    public function addReporte(\Entities\Reporte $reportes)
    {
        $this->__load();
        return parent::addReporte($reportes);
    }

    public function getReportes()
    {
        $this->__load();
        return parent::getReportes();
    }

    public function setGradoReporte(\Entities\GradoReporte $gradoReporte = NULL)
    {
        $this->__load();
        return parent::setGradoReporte($gradoReporte);
    }

    public function getGradoReporte()
    {
        $this->__load();
        return parent::getGradoReporte();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titulo', 'comentario_sugerido', 'publico', 'campo_dataset', 'reportes', 'gradoReporte');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}