<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Documento
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Documento extends EntityRepository{

}