<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GradoReporte
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradoReporte extends EntityRepository
{
}