<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Participacion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Participacion extends EntityRepository{
	//Busca las participaciones con el orden y los filtros dados
	public function findWithOrdering($options = null){
		$qb = $this->_em->createQueryBuilder();

		$qb->from('Entities\Participacion', 'p');

		if(isset($options['total'])){

			$qb->select('COUNT(p.id)');

		}else{

			$qb->select('p');
            $qb->addOrderBy('p.'.$options['orderby'], $options['orderdir']);

		}
		
		if(!isset($options['all']))
			$qb->where('p.publicado = 1');

		if(isset($options['total'])){

			return $qb->getQuery()->getSingleScalarResult();

		}else{
            if(!isset($options['excel'])){
                $qb->setFirstResult($options['offset'])
                    ->setMaxResults($options['limit']);
            }
			$query = $qb->getQuery();

			return $query->getResult();

		}
	}
}