<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Sector
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sector extends EntityRepository{
	public function findByStringArray($aSectores){
		$sectores = array();
		if($aSectores){
			foreach ($aSectores as $key => $sector) {
				$nombre = preg_replace('/\s\(.*\)/', '', $sector);
        $tipo = preg_match('/\(.*\)/', $sector, $matches);
        $tipo = preg_replace('/(\(|\))/', '', $matches[0]);
        $sectores[] = $this->findOneBy(array('nombre' => $nombre, 'tipo' => $tipo));
			}
		}
		return $sectores;
	}
}