<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Suscripcion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Suscripcion extends EntityRepository{

}