<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Tag
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tag extends EntityRepository{

  public function findPopulares($cantidad=NULL){

		$qb = $this->_em->createQueryBuilder();

		$qb->select('t, COUNT(d.id) AS ndatasets')
			->from('Entities\Tag', 't')
			->leftJoin('t.datasets', 'd')
			->where('d.publicado = 1 AND d.maestro = 0')
			->groupBy('t.id')
			->orderBy('ndatasets', 'DESC');
		if($cantidad)
			$qb->setMaxResults($cantidad);

		$query = $qb->getQuery();

		$result = $query->getResult();

		return $result;
		
	}

}