<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Vista
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vista extends EntityRepository
{
    public function getByDatasetAndFecha($datasetId, $fecha){
        $qb = $this->_em->createQueryBuilder();

        $qb->select('v')
             ->from('Entities\Vista', 'v')
             ->leftJoin('v.dataset', 'd')
             ->where('d.id = :datasetid AND v.fecha = :fecha')
             ->setParameters(array(
                    'datasetid' => $datasetId,
                    'fecha' => $fecha
                ))
             ->setMaxResults(1);

        $vista = $qb->getQuery()->getResult();

        if($vista)
            return $vista[0];
        else
            return false;
    }
}